pipeline {
  agent any
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn clean install'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'npm run build' // Specify the script name as needed
      }
    }
   // stage('DB') {
   //   agent {
     //   docker { image 'mysql:latest' }
     // }
     // steps {
        // Assuming you have a MySQL client installed, connect to the DB and run the SQL query
       // sh 'mysql -h <hostname> -u <username> -p<password> -e "SELECT * FROM STUDENT_TABLE;"'
      //}
    }
  }
}
